CREATE TABLE "TB_BICICLETA"
(	"ID_BICICLETA" NUMBER(19,0),
     "TIPO_BICICLETA" VARCHAR2(255 CHAR),
     "DONO" VARCHAR2(255 CHAR)
) ;


CREATE UNIQUE INDEX  "IDX_TB_BICICLETA_ID" ON  "TB_BICICLETA" ("ID_BICICLETA");
--------------------------------------------------------

ALTER TABLE  "TB_BICICLETA" MODIFY ("ID_BICICLETA" NOT NULL ENABLE);
ALTER TABLE  "TB_BICICLETA" ADD PRIMARY KEY ("ID_BICICLETA");

CREATE SEQUENCE  "SQ_BICICLETA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

DROP TABLE TB_BICICLETA;

CREATE TABLE "TB_CLIENTE"
(	"ID_CLIENTE" NUMBER(19,0),
     "NM_CLIENTE" VARCHAR2(255 CHAR),
     "ENDERECO" VARCHAR2(255 CHAR),
     "NR_CPF" NUMERIC(11)
) ;


CREATE UNIQUE INDEX  "IDX_TB_CLIENTE_ID" ON  "TB_CLIENTE" ("ID_CLIENTE");

--------------------------------------------------------

ALTER TABLE  "TB_CLIENTE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
ALTER TABLE  "TB_CLIENTE" ADD PRIMARY KEY ("ID_CLIENTE");

CREATE SEQUENCE  "SQ_CLIENTE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


