CREATE TABLE "TB_BICICLETA"
(	"ID_BICICLETA" NUMBER(19,0),
     "TIPO_BICICLETA" VARCHAR2(255 CHAR),
     "DONO" VARCHAR2(255 CHAR)
) ;


CREATE UNIQUE INDEX  "IDX_TB_BICICLETA_ID" ON  "TB_BICICLETA" ("ID_BICICLETA");
--------------------------------------------------------
--  Constraints for Table TB_ARTIST
--------------------------------------------------------

ALTER TABLE  "TB_BICICLETA" MODIFY ("ID_BICICLETA" NOT NULL ENABLE);
ALTER TABLE  "TB_BICICLETA" ADD PRIMARY KEY ("ID_BICICLETA");